### ISSUE TITLE
Add hexbin map to viz

### ISSUE THREAD

**Issue by hcorson-dosch-usgs** [usgs-makerspace/temperature-prediction#80]
* Place at end of ch. 2 - see [text document](https://doimspp.sharepoint.com/sites/gs-wma-iidd-makerspace/_layouts/15/Doc.aspx?OR=teams&action=edit&sourcedoc={28AF7BCE-11DB-40EE-A6F1-26BD0C81598F}) for guidance

**Comment by cnell-usgs** [comment]
This is what we are working with, open to suggested edits

![usa_hex_map_80-01](https://user-images.githubusercontent.com/17803537/100766519-58b51f80-33be-11eb-9a43-a100f64868ae.png)

**Comment by hcorson-dosch-usgs** [comment]
I think this looks AWESOME. I do think it would be helpful to indicate the DRB somehow - either by circling that general area and adding an annotation, or by adding in a watershed boundary in white. I think you'd tried the latter here, which made us realize the hex binning would really affect how observed a viewer would perceive the DRB to be:
![image](https://user-images.githubusercontent.com/54007288/100777348-4d1c2580-33cb-11eb-85e9-0ced3c401332.png)

I was thinking that if we did do the latter, we could make the boundary conform to the hexagonal geometry. It would get pretty inaccurate but I think that would be ok - since we show the real boundary elsewhere, and from a cartographic perspective hexbin maps naturally distort geometry anyway, so we might as well play that up. That would look something like this:
![image](https://user-images.githubusercontent.com/54007288/100777316-442b5400-33cb-11eb-8fd4-ce690f099fd4.png)

Thoughts? Too inaccurate? Worth exploring/trying with slightly different hex sizes?

@ellenbechtel @lindsayplatt Any other ideas about how we could highlight the DRB here?

**Comment by lindsayplatt** [comment]
These maps are incredible!

I don't think calling attention to the DRB using the hex outlines vs the actual DRB outline is bad. Since this is all about general patterns for temp observations around the country, I don't think it needs to be extremely accurate. I actually think that sticking with the hex shapes will make it easier to understand than adding the actual watershed outline where it cuts across some hexes. 

The white is kind of difficult to see though. Especially, when you are trying to figure out the right boundary because it is next to bright yellow. I am trying to think what alternative colors or ways of emphasizing the DRB hex shapes we could use 🤔
